# Generated by Django 6.0.3 on 2026-03-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_clinica_plan_suscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='es_psicologo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('PSICOLOGO', 'Psicólogo'), ('PACIENTE', 'Paciente')], default='PSICOLOGO', max_length=20),
        ),
    ]
